### PR TITLE
Polish: add jetbrains notnull & nullable annotations

### PR DESCRIPTION
**Pull request by JanStureNielsen**
Add jetbrains `@NotNull` and `@Nullable` annotation library as a managed dependency and add the `notnull-instrumenter-maven-plugin`.

### CODE REVIEW

**Comment by RobAustin** [comment]
java parent pom - 1.1.18 is now released to maven central

**Comment by RobAustin** [comment]
all project should be updated to use this new java parent pom - 1.1.18

**Comment by JanStureNielsen** [comment]
Hi @RobAustin -- is there a document or script describing the OpenHFT release process?

**Comment by RobAustin** [comment]
We use a TeamCity server and a closed source release project to perform the release, so this is not something that I can give you access to at the moment.

**Comment by RobAustin** [comment]
As a side note, if you've made changes to a project, for example, chronicle-bytes and you want that change to be available in the next release, you have to change the chronicle-bom to point to the latest snapshot version of bytes, our release process automatically will release any project on a snapshot version. We have to kick off the release projects manually, but also changing it to a snapshot is a good idea because the snapshot artifacts will get integrated into projects that use them and run through our CI system.  Thus picking up any issues ASAP

**Pull request merged**
